language: python
cache: pip

matrix:
  include:
    - { python: '3.6', env: TOXENV=py36 }

    # XXX (2018-08-10): Work around Travis shenanigans for Python 3.7:
    # https://github.com/travis-ci/travis-ci/issues/9815
    - { python: '3.7', env: TOXENV=py37, dist: xenial, sudo: true }

    # Codecov reporting:
    - { python: '3.6', env: TOXENV=py36-codecov }

install:
  - pip install tox

script:
  - tox
