language: python
cache: pip

matrix:
  include:
    - { python: '3.6', env: TOXENV=py36-dj2.0 }
    - { python: '3.6', env: TOXENV=py36-dj2.1 }
    - { python: '3.7', env: TOXENV=py37-dj2.0 }
    - { python: '3.7', env: TOXENV=py37-dj2.1 }
    # Codecov reporting:
    - { python: '3.6', env: TOXENV=py36-dj2.1-codecov }
  allow_failures:
    - python: '3.7'  # Travis doesn't support Python 3.7 yet.

install:
  - pip install tox

script:
  - tox
