language: python
cache: pip

matrix:
  include:
    - { python: '3.6', env: TOXENV=py36-dj2.0 }
    - { python: '3.6', env: TOXENV=py36-dj2.1 }

    # XXX (2018-08-10): Work around Travis shenanigans for Python 3.7:
    # https://github.com/travis-ci/travis-ci/issues/9815
    - { python: '3.7', env: TOXENV=py37-dj2.0, dist: xenial, sudo: true }
    - { python: '3.7', env: TOXENV=py37-dj2.1, dist: xenial, sudo: true }

    # Codecov reporting:
    - { python: '3.6', env: TOXENV=py36-dj2.1-codecov }

install:
  - pip install tox

script:
  - tox

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-west-1"
  app: "buza-website"
  env: "buza-testing"
  bucket_name: "elasticbeanstalk-eu-west-1-134668310374"
  on:
    branch: elastic-beanstalk
