# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20180618_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='star_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='star_question',
            field=models.BooleanField(default=False),
        ),
    ]
