# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vote', '0004_auto_20170110_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user_id', 'content_type', 'object_id', 'action', 'star')]),
        ),
    ]
