# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_boards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author_id',
            new_name='user',
        ),
    ]
