# Generated by Django 2.0.7 on 2018-07-12 14:34

import buza.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='phone number')),
                ('username', models.CharField(blank=True, max_length=15, unique=True, verbose_name='user name')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='school name')),
                ('school_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='school address')),
                ('grade', models.IntegerField(blank=True, default=7)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d', verbose_name='profile photo')),
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name and surname')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', buza.managers.UserManager()),
            ],
        ),
    ]
