# Generated by Django 2.0.7 on 2018-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(to='buza.Subject'),
        ),
    ]
