# Generated by Django 2.0.7 on 2018-08-17 22:31

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('buza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buza.Question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buza_questiontopic_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=taggit.managers.TaggableManager(help_text='List all the relevant topics for this question. \nExample: Triangles, Equations, Photosynthesis.', through='buza.QuestionTopic', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
