# Generated by Django 2.0.7 on 2018-08-15 18:13

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('buza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buza.Question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buza_tag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='buza.Tag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
