# Generated by Django 2.1 on 2018-08-21 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buza', '0002_add_question_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=7, help_text='Which grade it this question most relevant for? \nBy default this should be the grade that you are in.', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
    ]
