# Generated by Django 2.1.2 on 2018-10-20 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buza', '0003_question_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontopic',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='questiontopic',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True, help_text='Give a detailed description of your question', verbose_name='Question Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(help_text='Which grade it this question most relevant for? By default this will be the grade that you are in.', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='Write a short sentence summarising your question', max_length=1024, verbose_name='Question Summary'),
        ),
        migrations.DeleteModel(
            name='QuestionTopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
