# Generated by Django 2.0.7 on 2018-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buza', '0003_auto_20180724_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='buza.Tag'),
        ),
    ]
