# Generated by Django 2.1 on 2018-08-25 15:42

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('buza', '0003_question_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True, help_text='Give a detailed description of your question', verbose_name='Question Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(help_text='Which grade it this question most relevant for? By default this will be the grade that you are in.', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='Write a short sentence summarising your question', max_length=1024, verbose_name='Question Summary'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=taggit.managers.TaggableManager(help_text='List all the relevant topics for this question. Example: Triangles, Equations, Photosynthesis.', through='buza.QuestionTopic', to='buza.Topic', verbose_name='Topics'),
        ),
    ]
