# Generated by Django 2.1.2 on 2018-11-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buza', '0004_remove_question_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_title',
            field=models.TextField(default='EMS'),
            preserve_default=False,
        ),
    ]
