# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20180603_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='media',
            field=models.ImageField(upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.ImageField(upload_to='questions/'),
        ),
    ]
